pipeline {
    agent any
    
    tools {
        maven 'maven-3'
        jdk 'jdk-21'
    }
    
    environment {
        SERVICE = 'account'
        NAME = "henriquessm/${env.SERVICE}"
        REGISTRY_CREDENTIALS = 'dockerhub-credentials'
        AWS_REGION = "us-east-1"
        CLUSTER_NAME = "projeto-humberto"
    }
    
    stages {
        stage('Checkout Dependencies') {
            steps {
                script {
                    dir('libs/account') {
                        git branch: 'main', url: 'https://github.com/henriquessm/store-account.git'
                        sh 'mvn clean install -DskipTests'
                    }
                }
            }
        }

        stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }      
        
        stage('Build & Push Image') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: env.REGISTRY_CREDENTIALS, 
                                                   usernameVariable: 'USERNAME', 
                                                   passwordVariable: 'TOKEN')]) {
                        sh """
                            docker login -u \$USERNAME -p \$TOKEN
                            docker build -t ${env.NAME}:latest .
                            docker build -t ${env.NAME}:${env.BUILD_NUMBER} .
                            docker push ${env.NAME}:latest
                            docker push ${env.NAME}:${env.BUILD_NUMBER}
                        """
                    }
                }
            }
        }

        stage('Deploy to EKS') {
            steps {
                withCredentials([string(credentialsId: 'aws-creds-profile', variable: 'AWS_PROFILE')]) {
                    sh """
                        aws eks --region $AWS_REGION update-kubeconfig --name $CLUSTER_NAME
                        kubectl set image deployment/account account=$NAME:${BUILD_NUMBER}
                    """
                }
            }
        }
    }
}
